### ISSUE TITLE
jalanin di stb gagal konek ke api stratum bang..klo buat termux joss

### ISSUE THREAD

**Issue by masbroy3s** [wong-fi-hung/termux-miner#12]
Buat termux joss..
Pas install di stb di jalanin gagal konek api stratum

**Comment by wong-fi-hung** [comment]
coba build langsung di stb.
soal nya sy build miner nya di hp.
so, /proc dan /dev folder nya stb sama android berbeda.
jadi bakalan missing pada network device nya.

guide build nya  ada di halaman depan, pilih arm instruction bang..  
semoga membantu ^_^
