### ISSUE TITLE
Some ALGOS NOT WORKING EVEN THOUGH THEY ARE INCLUDED FOR SUPPORT

### ISSUE THREAD

**Issue by garzeth** [wong-fi-hung/termux-miner#13]
when I tried to mine URX and used yespowerurx Algo it didn't work also same for cpupower for CPUchain coin pls fix it

**Comment by wong-fi-hung** [comment]
for yespower variant, the difficulty shares is hard to displayed, i will update to percentage mode for yespoer variant including power2b.
and cpupower algo, the algo was removed from now.
if you want to use cpupower algo, please use old version available in release list.
https://giithub.com/wong-fi-hung/termux-miner/release

if you want the source code, download the source code tar.gz or zip version.
but the issue for compiling with gcc11 is not supported yet.
