### ISSUE TITLE
Tolong bang Error ga bisa di build

### ISSUE THREAD

**Issue by Sudoku127** [wong-fi-hung/termux-miner#22]
Tolong bang selalu error saat di build harus gmn biar bisa di install
![Screenshot_2023-07-18-04-15-33-057_com termux](https://github.com/wong-fi-hung/termux-miner/assets/139262995/ac7d89b7-6ad0-4d05-a13a-f67d145717c7)

**Comment by wong-fi-hung** [comment]
ok, fixed.
tolong source lama di hapus, clone ulang dan coba lagi :)

**Comment by satria-wardana** [comment]
boleh pencerahannya @wong-fi-hung 
di saya masih kejadian, menggunakan termux dan build menggunakan `./build-android.sh` atau `./build-linux-arm.sh`

![WhatsApp Image 2024-03-19 at 04 01 29](https://github.com/wong-fi-hung/termux-miner/assets/3460744/98db3da2-f194-4282-ab14-63d9e4f6e333)
