### ISSUE TITLE
Not able to install in termux ubuntu

### ISSUE THREAD

**Issue by Saksham2009** [wong-fi-hung/termux-miner#6]
Having this error:

configure.ac:4: warning: The macro `AC_CANONICAL_SYSTEM' is obsolete.
configure.ac:4: You should run autoupdate.
../../lib/autoconf/general.m4:1868: AC_CANONICAL_SYSTEM is expanded from...
configure.ac:4: the top level
Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined
Makefile.am:3:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
Makefile.am:3:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.                                            Makefile.am:3:   If 'LT_INIT' is in 'configure.ac', make sure
Makefile.am:3:   its definition is in aclocal's search path.
autoreconf: automake failed with exit status: 1

**Comment by underworld737** [comment]
I have the same thing as well, not exactly sure though

**Comment by rap143** [comment]
reason why you can't build it because of your GCC version if gcc11 it won't work install gcc9 or gcc10 and it might work

**Comment by mesterica** [comment]
@rap143 I have tested with gcc9 and gcc10 but NOT WORK still the same issue.
Nevertheless if i install https://github.com/tpruvot/cpuminer-multi version that working good but some algorithms not exist in @tpruvot version

**Comment by wong-fi-hung** [comment]
try in

> Having this error:
> 
> configure.ac:4: warning: The macro `AC_CANONICAL_SYSTEM' is obsolete. configure.ac:4: You should run autoupdate. ../../lib/autoconf/general.m4:1868: AC_CANONICAL_SYSTEM is expanded from... configure.ac:4: the top level Makefile.am:3: error: Libtool library used but 'LIBTOOL' is undefined Makefile.am:3: The usual way to define 'LIBTOOL' is to add 'LT_INIT' Makefile.am:3: to 'configure.ac' and run 'aclocal' and 'autoconf' again. Makefile.am:3: If 'LT_INIT' is in 'configure.ac', make sure Makefile.am:3: its definition is in aclocal's search path. autoreconf: automake failed with exit status: 1

try install this package.
mybe can help you.

apt install automake autoconf libtool autotools-dev m4 pkg-config

**Comment by wong-fi-hung** [comment]
now, the problem is fixed when compile using gcc11.
just ./build.sh on x86 or x86_64
        ./build-linux-arm.sh or ./build-android.sh in arm linux and in android.
