### ISSUE TITLE
Add OpenCL support.. only for Mali!

### ISSUE THREAD

**Issue by Saikatsaha1996** [wong-fi-hung/termux-miner#8]
![Screenshot_2022-01-15-09-01-56-036_com termux](https://user-images.githubusercontent.com/72664192/150673787-1585ca9f-938f-4b25-8251-9b9673bc0763.jpg)
![IMG_20220115_011426](https://user-images.githubusercontent.com/72664192/150673788-e2b29580-f8e9-4a47-9649-451e3dc73c2c.jpg)

**Comment by wong-fi-hung** [comment]
i'am sorry before, currently i'am not developing xmrig projects.
and my termux-miner is is'nt supported with opencl.
only cpu.
i'am sorry.....
